### PR TITLE
Added FormSumbit to newsletter subscription

### PR DESCRIPTION
**Pull request by michagodfrey**
I used FormSubmit to send you an email when entered in the input. (great tool I'm glad I know about it now).

I made it so the user would get an alert when submitting, rather than the default process of being redirected to a captcha and another page. 

I'm happy to change it if you'd prefer to have a captcha etc.

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]

**Comment by KendallDoesCoding** [comment]
Perfect! you did a amazing job on this.

**Comment by KendallDoesCoding** [comment]
I've merged this in but I'm having a issue to activate the form, will do it later.

Please remind me @michagodfrey

**Comment by michagodfrey** [comment]
Oh no, that's annoying. What's the issue exactly? I noticed when I was testing whenever I used it in a new browser I had to go through the activation process again.

**Comment by KendallDoesCoding** [comment]
Yes. Because you have to activate it once for a domain, and you were doing
it locally.

It seems that my email SMTP was taking a while to process to email with the
activation just now, but I've activated the form, you can do a test on the
main site if you like. It's working now:
https://bootstrap.course.kendalldoescoding.gq/
<https://jebcco.com/click?redirect=https%3A%2F%2Fbootstrap.course.kendalldoescoding.gq%2F&dID=1664182005671&linkName=https://bootstrap.course.kendalldoescoding.gq/>
.

Thanks a lot

**Comment by michagodfrey** [comment]
Glad to hear it. I just sent a test email.

**Comment by KendallDoesCoding** [comment]
Yes, recieved it.

**Pull request merged**
